### ISSUE TITLE
Scratchify doesn't play songs on Chrome

### ISSUE THREAD

**Issue by mdwalters** [Streamilator/Streamilator#2]
I typed in the number for the first song, and nothing plays.

**Comment by Mwalters75** [comment]
Doesn't do anything.

**Comment by catonmeower** [comment]
Seems like it's an issue with the extension. It should work even when not injected (I tested it). What browser are you using?

**Comment by underfanreal** [comment]
The first song has silence before it starts, try waiting about 15 seconds

**Comment by mdwalters** [comment]
closing as this is more stale than the moldy bread on top of my fridge, and i can hear now
